import 'package:flutter/material.dart';
import 'package:intl/intl.dart';

class ForecastPage extends StatelessWidget {
  const ForecastPage({super.key});

  @override
  Widget build(BuildContext context) {
    final simulatedForecast = {
      "predictedWeight": "850g",
      "harvestDate": DateFormat(
        'MMMM dd, yyyy',
      ).format(DateTime.now().add(const Duration(days: 7))),
      "confidence": "94%",
      "temperature": "29°C",
      "waterQuality": "Good",
    };

    return Scaffold(
      body: Column(
        children: [
          // 🌈 Gradient Header
          Container(
            width: double.infinity,
            padding: const EdgeInsets.only(top: 60, bottom: 40),
            decoration: const BoxDecoration(
              gradient: LinearGradient(
                colors: [Color(0xFF00AEEF), Color(0xFF00AEEF)],
                begin: Alignment.topLeft,
                end: Alignment.bottomRight,
              ),
              borderRadius: BorderRadius.only(
                bottomLeft: Radius.circular(30),
                bottomRight: Radius.circular(30),
              ),
            ),
            child: const Center(
              child: Column(
                children: [
                  Icon(Icons.analytics_outlined, size: 60, color: Colors.white),
                  SizedBox(height: 10),
                  Text(
                    "Harvest Forecast",
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 26,
                      fontWeight: FontWeight.bold,
                      letterSpacing: 1.2,
                    ),
                  ),
                  SizedBox(height: 5),
                  Text(
                    "Powered by ToTepAI Prediction Model",
                    style: TextStyle(color: Colors.white70, fontSize: 14),
                  ),
                ],
              ),
            ),
          ),

          // 📊 Forecast Information Card
          Expanded(
            child: SingleChildScrollView(
              padding: const EdgeInsets.all(16),
              child: Card(
                shape: RoundedRectangleBorder(
                  borderRadius: BorderRadius.circular(20),
                ),
                elevation: 4,
                child: Padding(
                  padding: const EdgeInsets.all(20),
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.start,
                    children: [
                      const Text(
                        "AI Forecast Results",
                        style: TextStyle(
                          fontSize: 22,
                          fontWeight: FontWeight.bold,
                          color: Colors.black87,
                        ),
                      ),
                      const SizedBox(height: 16),
                      infoRow(
                        "Predicted Weight:",
                        simulatedForecast["predictedWeight"]!,
                      ),
                      infoRow(
                        "Estimated Harvest Date:",
                        simulatedForecast["harvestDate"]!,
                      ),
                      infoRow(
                        "Confidence Level:",
                        simulatedForecast["confidence"]!,
                      ),
                      infoRow(
                        "Average Temperature:",
                        simulatedForecast["temperature"]!,
                      ),
                      infoRow(
                        "Water Quality:",
                        simulatedForecast["waterQuality"]!,
                      ),
                      const SizedBox(height: 20),
                      const Text(
                        "This forecast is generated by the ToTepAI intelligent model based on environmental and growth data from your fish pond.",
                        style: TextStyle(color: Colors.black54, height: 1.4),
                      ),
                    ],
                  ),
                ),
              ),
            ),
          ),
        ],
      ),
    );
  }

  Widget infoRow(String title, String value) {
    return Padding(
      padding: const EdgeInsets.symmetric(vertical: 8),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Expanded(
            flex: 2,
            child: Text(
              title,
              style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 16),
            ),
          ),
          const SizedBox(width: 8),
          Expanded(
            flex: 3,
            child: Text(
              value,
              textAlign: TextAlign.right,
              softWrap: true,
              overflow: TextOverflow.visible,
              style: const TextStyle(
                fontSize: 16,
                color: Colors.black87,
                letterSpacing: 0.3,
              ),
            ),
          ),
        ],
      ),
    );
  }
}
